[build]
  publish = "www"
  command = "echo 'No build command needed for static site'"

[[headers]]
  for = "/*"
  [headers.values]
    # Basic security headers to look "proper" to firewalls
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
